### ISSUE TITLE
TODO for missing functionalities

### ISSUE THREAD

**Issue by 17ms** [17ms/quickbin#1]
- [x] Session-store (& cookie configuration) to make sessions persistent despite server restarts
- [x] Shellscript to run migrations
- [x] Proper logging to replace console.log()
- [x] Removal of posts older than 1 week
- [x] New passport-strategy for updating password, also logout-functionality
